### ISSUE TITLE
no support php8

### ISSUE THREAD

**Issue by xiusin** [phalcon/dd#16]
Problem 1
    - Root composer.json requires phalcon/dd v1.1.3 -> satisfiable by phalcon/dd[v1.1.3].
    - phalcon/dd v1.1.3 requires php ^5.4 || ^7.0 -> your php version (8.1.12) does not satisfy that requirement.

**Comment by Jeckerson** [comment]
Use v2.0.0 (https://github.com/phalcon/dd/releases/tag/v2.0.0)

<img width="218" alt="image" src="https://user-images.githubusercontent.com/3289702/202906595-42cbf1c7-cf84-4138-b4da-5153a8031933.png">
